
package lt.viko.webservices.rkomaristova.jaxws.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DragonServiceImpl", targetNamespace = "http://services.jaxws.rkomaristova.webservices.viko.lt/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DragonServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns lt.viko.webservices.rkomaristova.jaxws.services.Dragon
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDragonByName", targetNamespace = "http://services.jaxws.rkomaristova.webservices.viko.lt/", className = "lt.viko.webservices.rkomaristova.jaxws.services.GetDragonByName")
    @ResponseWrapper(localName = "getDragonByNameResponse", targetNamespace = "http://services.jaxws.rkomaristova.webservices.viko.lt/", className = "lt.viko.webservices.rkomaristova.jaxws.services.GetDragonByNameResponse")
    @Action(input = "http://services.jaxws.rkomaristova.webservices.viko.lt/DragonServiceImpl/getDragonByNameRequest", output = "http://services.jaxws.rkomaristova.webservices.viko.lt/DragonServiceImpl/getDragonByNameResponse")
    public Dragon getDragonByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns lt.viko.webservices.rkomaristova.jaxws.services.Princess
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPrincessStolenByDragonName", targetNamespace = "http://services.jaxws.rkomaristova.webservices.viko.lt/", className = "lt.viko.webservices.rkomaristova.jaxws.services.GetPrincessStolenByDragonName")
    @ResponseWrapper(localName = "getPrincessStolenByDragonNameResponse", targetNamespace = "http://services.jaxws.rkomaristova.webservices.viko.lt/", className = "lt.viko.webservices.rkomaristova.jaxws.services.GetPrincessStolenByDragonNameResponse")
    @Action(input = "http://services.jaxws.rkomaristova.webservices.viko.lt/DragonServiceImpl/getPrincessStolenByDragonNameRequest", output = "http://services.jaxws.rkomaristova.webservices.viko.lt/DragonServiceImpl/getPrincessStolenByDragonNameResponse")
    public Princess getPrincessStolenByDragonName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
