
package lt.viko.webservices.rkomaristova.jaxws.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DragonServiceImplService", targetNamespace = "http://services.jaxws.rkomaristova.webservices.viko.lt/", wsdlLocation = "http://localhost:8085/my/dragonservice?wsdl")
public class DragonServiceImplService
    extends Service
{

    private final static URL DRAGONSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DRAGONSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName DRAGONSERVICEIMPLSERVICE_QNAME = new QName("http://services.jaxws.rkomaristova.webservices.viko.lt/", "DragonServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/my/dragonservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DRAGONSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        DRAGONSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public DragonServiceImplService() {
        super(__getWsdlLocation(), DRAGONSERVICEIMPLSERVICE_QNAME);
    }

    public DragonServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DRAGONSERVICEIMPLSERVICE_QNAME, features);
    }

    public DragonServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, DRAGONSERVICEIMPLSERVICE_QNAME);
    }

    public DragonServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DRAGONSERVICEIMPLSERVICE_QNAME, features);
    }

    public DragonServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DragonServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DragonServiceImpl
     */
    @WebEndpoint(name = "DragonServiceImplPort")
    public DragonServiceImpl getDragonServiceImplPort() {
        return super.getPort(new QName("http://services.jaxws.rkomaristova.webservices.viko.lt/", "DragonServiceImplPort"), DragonServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DragonServiceImpl
     */
    @WebEndpoint(name = "DragonServiceImplPort")
    public DragonServiceImpl getDragonServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.jaxws.rkomaristova.webservices.viko.lt/", "DragonServiceImplPort"), DragonServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DRAGONSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw DRAGONSERVICEIMPLSERVICE_EXCEPTION;
        }
        return DRAGONSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
