
package lt.viko.webservices.rkomaristova.jaxws.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DragonServiceImpl", targetNamespace = "http://services.jaxws.rkomaristova.webservices.viko.lt/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DragonServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns lt.viko.webservices.rkomaristova.jaxws.services.Dragon
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDragonByName", targetNamespace = "http://services.jaxws.rkomaristova.webservices.viko.lt/", className = "lt.viko.webservices.rkomaristova.jaxws.services.GetDragonByName")
    @ResponseWrapper(localName = "getDragonByNameResponse", targetNamespace = "http://services.jaxws.rkomaristova.webservices.viko.lt/", className = "lt.viko.webservices.rkomaristova.jaxws.services.GetDragonByNameResponse")
    @Action(input = "http://services.jaxws.rkomaristova.webservices.viko.lt/DragonServiceImpl/getDragonByNameRequest", output = "http://services.jaxws.rkomaristova.webservices.viko.lt/DragonServiceImpl/getDragonByNameResponse")
    public Dragon getDragonByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns lt.viko.webservices.rkomaristova.jaxws.services.Dragon
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createDragon", targetNamespace = "http://services.jaxws.rkomaristova.webservices.viko.lt/", className = "lt.viko.webservices.rkomaristova.jaxws.services.CreateDragon")
    @ResponseWrapper(localName = "createDragonResponse", targetNamespace = "http://services.jaxws.rkomaristova.webservices.viko.lt/", className = "lt.viko.webservices.rkomaristova.jaxws.services.CreateDragonResponse")
    @Action(input = "http://services.jaxws.rkomaristova.webservices.viko.lt/DragonServiceImpl/createDragonRequest", output = "http://services.jaxws.rkomaristova.webservices.viko.lt/DragonServiceImpl/createDragonResponse")
    public Dragon createDragon(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns lt.viko.webservices.rkomaristova.jaxws.services.Princess
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPrincessStolenByDragonName", targetNamespace = "http://services.jaxws.rkomaristova.webservices.viko.lt/", className = "lt.viko.webservices.rkomaristova.jaxws.services.GetPrincessStolenByDragonName")
    @ResponseWrapper(localName = "getPrincessStolenByDragonNameResponse", targetNamespace = "http://services.jaxws.rkomaristova.webservices.viko.lt/", className = "lt.viko.webservices.rkomaristova.jaxws.services.GetPrincessStolenByDragonNameResponse")
    @Action(input = "http://services.jaxws.rkomaristova.webservices.viko.lt/DragonServiceImpl/getPrincessStolenByDragonNameRequest", output = "http://services.jaxws.rkomaristova.webservices.viko.lt/DragonServiceImpl/getPrincessStolenByDragonNameResponse")
    public Princess getPrincessStolenByDragonName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addKnightEatenByDragonName", targetNamespace = "http://services.jaxws.rkomaristova.webservices.viko.lt/", className = "lt.viko.webservices.rkomaristova.jaxws.services.AddKnightEatenByDragonName")
    @ResponseWrapper(localName = "addKnightEatenByDragonNameResponse", targetNamespace = "http://services.jaxws.rkomaristova.webservices.viko.lt/", className = "lt.viko.webservices.rkomaristova.jaxws.services.AddKnightEatenByDragonNameResponse")
    @Action(input = "http://services.jaxws.rkomaristova.webservices.viko.lt/DragonServiceImpl/addKnightEatenByDragonNameRequest", output = "http://services.jaxws.rkomaristova.webservices.viko.lt/DragonServiceImpl/addKnightEatenByDragonNameResponse")
    public void addKnightEatenByDragonName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns lt.viko.webservices.rkomaristova.jaxws.services.Dragon
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteDragonByName", targetNamespace = "http://services.jaxws.rkomaristova.webservices.viko.lt/", className = "lt.viko.webservices.rkomaristova.jaxws.services.DeleteDragonByName")
    @ResponseWrapper(localName = "deleteDragonByNameResponse", targetNamespace = "http://services.jaxws.rkomaristova.webservices.viko.lt/", className = "lt.viko.webservices.rkomaristova.jaxws.services.DeleteDragonByNameResponse")
    @Action(input = "http://services.jaxws.rkomaristova.webservices.viko.lt/DragonServiceImpl/deleteDragonByNameRequest", output = "http://services.jaxws.rkomaristova.webservices.viko.lt/DragonServiceImpl/deleteDragonByNameResponse")
    public Dragon deleteDragonByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
